title: XiaoChangBai
description: study hard and make progress every day.
author: Xiao Chang Bai
avatar: /assets/images/identicon.png
email: 704566072@qq.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
#twitter:
#  username: ngzhio
#  card: summary
logo: /assets/images/identicon.png
social:
  name: Xiao Chang Bai
  links:
    - https://gitee.com/xiaochangbai
    - https://github.com/xiaochangbai
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
