# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: XiaoChangBai

defaults:
  -
    scope:
      path: "a" # empty string for all files
    values:
      title: XiaoChangBai

description: 为往圣继绝学
author:
  name: XiaoChangBai
  email: 704566072@qq.com
  github: xiaochangbai
  bio: 为往圣继绝学!
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
